### ISSUE TITLE
OnClickListener for InputFields

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#150]
Hi there,

I'm wondering if it's possible to add a onClickListener to a InputField.

My case is the following:

I have a NumberInput which is disabled in some cases. If the user still clicks the field I want to show some alert with the reason why the value can not be changed. Any ideas how I can achieve this?

I'm looking forward to some help.

Best,
Daniel

**Comment by TheJuki** [comment]
I just released [6.4.3](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency. Unfortunately, Android disables click and touch events when a view is disabled. So, I added focusable and clickable as booleans. You will need to set focusable to false and use the new onClick unit.

**Comment by darkwood-studios** [comment]
Hey @TheJuki  - thanks for your fast response!

The clickEvent is not called in my code. Please see this example:

```
number(FormField.ZIP) {
                title = "Zip Code"
                required = true
                value = customer.zip
                numbersOnly = true
                clearOnFocus = true
                maxLength = 5
                enabled = !locked // false for locked
                focusable = !locked // false for locked
                clickable = locked // true for locked
                onClick = {
if(locked) {
alert("message")
}
                }
                valueObservers.add { newValue, _ ->
                    if (newValue?.length == 5) {
                        zipCode = newValue
                        loadOfflineData()
                    }
                }
            }
```

**Comment by TheJuki** [comment]
`enabled = !locked // false for locked`

Remove that line. Android disables click and touch events when a view is disabled.

If you need to change the color of the form element when it is enabled then use backgroundColor, valueTextColor, and titleTextColor.

**Comment by darkwood-studios** [comment]
Still not working... this is the complete code:

`// zip
            number(FormField.ZIP) {
                title = "Zip code *"
                required = true
                value = customer?.zip
                numbersOnly = true
                clearOnFocus = true
                maxLength = 5
                focusable = lockedZipCode == null // focusable = false for locked zip
                clickable = lockedZipCode != null // clickable = true for locked zip
                onClick = {
                    // todo this one is not called
                    if(lockedZipCode != null) {
                        alert("Zip code locked!")
                    }
                }
                valueObservers.add { newValue, _ ->
                    if (newValue?.length == 5) {
                        zipCode = newValue
                        doSomethingWithNewZip()
                    }
                }
            }`

**Comment by TheJuki** [comment]
The click event works for me when lockedZipCode is not null in your example.

**Comment by darkwood-studios** [comment]
Now it's working.

The problem is the anko.alert when i call it from within the onClick (maybe it's loosing the context)

Now I've created a wrapper method for the alert in my parent fragment and now it's fine. Thank you for your great work!
