### ISSUE TITLE
Ability to change background and text color of input

### ISSUE THREAD

**Issue by darkwood-studios** [TheJuki/KFormMaster#48]
Hi there,

I'm still working on my zip code input field. I want to change the background color to a light green and the text color to a dark green if the entered zip code matches my post data. If the zip code is invalid I want to change it to red.

I imagined something like 
`formBuilder.getFormElement<FormNumberEditTextElement>(FormField.ZIP).setBackgroundColor(...)`

Any idea to make this happen?

**Comment by TheJuki** [comment]
I just released [4.7.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency and let me know if setBackgroundColor works for you. Check out the docs: https://thejuki.github.io/KFormMaster/element/base/#background-color

**Comment by ZuzanaBenicko** [comment]
Hello, I would like to ask if there is a possibility to change the appearance of the row on change with setValueObservers. With the code below nothing happens. What is the approach when I want to do something like that? (text.setTitleTextColor(Color.RED) works if I use it outside of setValueObservers)

text.getValueObservers().add((newValue, element) -> {
                        if (newValue.length() < MIN)){
                           text.setTitleTextColor(Color.RED);
                        }
                        return Unit.INSTANCE;
                    });

**Comment by TheJuki** [comment]
I am not sure what 'text' is here. 'text' may be the the builder class for FormSingleLineEditTextElement : https://github.com/TheJuki/KFormMaster/blob/master/form/src/main/java/com/thejuki/kformmaster/helper/FormBuilder.kt#L211

I would use 'element' inside the ValueObservers since it does point to the instance of the element and not the builder class.

**Comment by ZuzanaBenicko** [comment]
I am sorry, yes you are right text is the builder class. 
Unfortunately, I can not use it with the element. I tried to cast it in many ways, still getting error "Ambiguous method call setBackgroundColor (Integer) in BaseFormElement and setBackgroundColor (Integer) in BaseFormElement match"

text.getValueObservers().add((newValue, element) -> {
   if (newValue.length() < MIN)){
       element.setTitleTextColor(Color.RED);
   }
   return Unit.INSTANCE;
});

**Comment by ZuzanaBenicko** [comment]
Unfortunately no, still the same error. Compiler underlines input Integer(Color) value with the same error message.

**Comment by TheJuki** [comment]
I created a new issue for this @ZuzanaBenicko  #49. I am closing this issue as this Java method issue is unrelated. @darkwood-studios feel free to re-open.

**Comment by TheJuki** [comment]
@ZuzanaBenicko Issue #49 has been resolved. 

I just released [5.0.0](https://github.com/TheJuki/KFormMaster/releases/latest). Please update your dependency. Let me know if you have any issues using the set methods in Java.
